# Example config file

# Global options
[global]
verbose = false
trace = false

# Client options
[client]
scheme = "http" # [http, https]
host = "127.0.0.1"
port = 9292
path = "/"
connect_timeout = 5
inactivity_timeout = 5

# Server options
[server]
host = "127.0.0.1"
port = 9292
path = "/"

# Database options
[database]
type = "mysql" # [mysql]
host = "127.0.0.1"
database = "minicron"
username = "minicron"
password = "password"

# CLI options
[cli]
mode = "line" # [line, char]
dry_run = false

# Alerting options
[alerts]
  [alerts.email]
  enabled = false
  # from = "from@example.com"
  # to = "to@example.com"

  [alerts.sms]
  enabled = false
  # from = "+442222222222"
  # to = "+443333333333"
    [alerts.sms.twilio]
    # account_sid = "YOUR_TWILIO_ACCOUNT_SID"
    # auth_token = "YOUR_TWILIO_AUTH_TOKEN"
