# Example config file

# Global options
[global]
verbose = false

# Client options
[client]
scheme = "http" # [http, https]
host = "127.0.0.1"
port = 9292
path = "/"
connect_timeout = 5
inactivity_timeout = 5

# Server options
[server]
scheme = "http" # [http, https]
host = "127.0.0.1"
port = 9292
path = "/"

# Database options
[database]
type = "sqlite" # [mysql, sqlite]
# The options below are for mysql only
# host = "127.0.0.1"
# database = "minicron"
# username = "minicron"
# password = "password"

# CLI options
[cli]
mode = "line" # [line, char]
dry_run = false
trace = false
